### PR TITLE
Release version 0.3

### PR DESCRIPTION
**Pull request by birktj**
With a lot of bug fixes and both encoding and incremental decoding implemented I think that it is time for a new version of this library. This will also allow work in the `image` library to implement these new features there. 

Could somebody from @image-rs/publish acknowledge and proceed here?

### CODE REVIEW

**Comment by HeroicKatora** [comment]
@birktj The fuzz_images are seemingly a problem for `crates.io`.

```
$ cargo publish --dry-run
    Updating crates.io index
   Packaging tiff v0.3.0 (/home/andreas/code/projects/image-tiff)
error: failed to prepare local package for uploading

Caused by:
  cannot package a filename with a special character `:`: tests/fuzz_images/divide_by_zero/id:000000,sig:06,src:000036,op:havoc,rep:4
```

**Comment by HeroicKatora** [comment]
We should probably exclude that folder from the package content itself.

**Comment by birktj** [comment]
Hmm, if you think that is a good solution then I support it. If not I could simply rename the images.

**Comment by HeroicKatora** [comment]
Renaming the images will have to be done everytime new ones are generated as well, and is easy to forget. [We exclude the test and fuzz images in `image` as well](https://github.com/image-rs/image/blob/master/Cargo.toml#L21).

**Comment by HeroicKatora** [comment]
Well, tbh, it isn't quite comparable since the `afl` fuzzer is its own crate so that the fuzzing corpus for `afl` is never part of the actual crate to begin with.

**Comment by birktj** [comment]
@HeroicKatora I have excluded the images

**Comment by HeroicKatora** [comment]
Published :rocket:

**Pull request merged**
