### PR TITLE
Add horizontal predictor support

### PR DESCRIPTION
**Pull request by spoutn1k**
While investigating #237, I came to the realization that the crate lacked predictor support at encoding. This PR attemps to merge the feature in the most efficient way.

`TiffEncoder` gains a fluent interface `with_predictor` allowing users to easily set their preferred method. Using this predictor with the LZW compression makes its average compression ratio go from 0.85:1 (yes, the compressed image is bigger) to 1.3:1.

With those changes underway, the clunkyness of the current interface was just too strong. Having the compression as a generic type on the `ImageEncoder` methods serves no purpose other than complicating the code; methods were duplicated `x` and `x_with_compression` to account for the type. Adding the predictor to this interface was out of the question: `x` `x_with_compression` `x_with_predictor` `x_with_compression_and_predictor` ? No thanks.

`TiffEncoder` also gains a `with_compression` fluent interface to set the desired file compression.

The final interface looks as such:
```rs
let mut encoder = TiffEncoder::<std::fs::File>::new(compressed)?
        .with_predictor(Predictor::Horizontal)
        .with_compression(Compression::Lzw);

    encoder.write_image::<colortype::RGB8>(
        photo.width(),
        photo.height(),
        photo.as_rgb8().expect("Wrong image format"),
    )?;
```

```diff
-    let mut encoder = TiffEncoder::<std::fs::File>::new(compressed)?;
+    let mut encoder = TiffEncoder::<std::fs::File>::new(compressed)?
+        .with_predictor(Predictor::Horizontal)
+        .with_compression(Compression::Lzw);
+
+    encoder.write_image::<colortype::RGB8>(
-    encoder.write_image_with_compression::<colortype::RGB8, Compresion::Lzw>(
         photo.width(),
         photo.height(),
-        Compression::Lzw,
         photo.as_rgb8().expect("Wrong image format"),
+    )?;
```

This means the `*_with_compression` methods are gone from the `TiffEncoder` interface, which means breaking changes.

### CODE REVIEW

**Comment by spoutn1k** [comment]
Any feedback ? If the breaking changes are not welcome I can try and work around them but I was able to build `image-rs/image` with no issues

**Comment by spoutn1k** [comment]
Fixed the grammar incompatible with rust 1.61 ! Please re-run the tests I cannot do it manually :(

**Comment by spoutn1k** [comment]
Any feedback ? I am using this to compress my images using rust instead of an external tool and if it is helpful to me I'm sure it could help someone else.

**Comment by kornelski** [comment]
Creating a new `Vec` per row is wasteful. You could pass `&mut Vec` to the predictor and have it append pixels directly to the final buffer.

**Comment by spoutn1k** [comment]
Well maybe but the method this function is used does not allow for modification of the buffer it passes:

https://github.com/image-rs/image-tiff/blob/950811888dbc23e37e97264d9aafe3937620bcad/src/encoder/mod.rs#L467-L490

So there would be copy at some point or another. I can look into changing that but I wanted to limit my changes.

**Comment by kornelski** [comment]
You're calling collect() there which creates a Vec anyway. 
Don't use flat_map + collect(). Make Vec::with_capacity() and append to it

**Comment by spoutn1k** [comment]
`[T::Inner]` does not have `Clone`, so if I want to create the `Vec` outside the predictor function, I will need to have this ...

I pushed a version that does not collect and writes strips as soon as they are predicted. If returning a `Vec` is still a performance concern, I will update the `ColorType` trait to do so.

**Comment by kornelski** [comment]
Can you check that the tests actually work?

I've replaced the predictor code with nothing:

```rust
Predictor::Horizontal => {
                0
}
```

and `cargo test --all` still passes.

**Comment by kornelski** [comment]
This is what I mean: https://github.com/spoutn1k/image-tiff/pull/1

**Comment by spoutn1k** [comment]
You are right I did not implement tests. Will do that.

**Comment by spoutn1k** [comment]
While implementing the tests, something was not right and the changes you made were producing corrupted images. Implementing the tests first then adding your changes.

**Comment by spoutn1k** [comment]
Images are corrupted from e00fa6ba5da2da42e137d4901f51c76b5cf7d9b1. Looks like the encoder does not like writing strip by strip.

**Comment by spoutn1k** [comment]
Most of the round-trip tests fail for datatypes bigger than `u8`. After some testing and manually compressing images it seems the implementation of the "deprediction" in the decoder is the culprit.

**Comment by spoutn1k** [comment]
Fixes #237 and #247 !

**Review by kornelski — APPROVED** [review]

**Comment by kornelski** [comment]
Thank you

**Comment by spoutn1k** [comment]
Thank you !

**Pull request merged**
