### PR TITLE
Update jpeg-decoder to 0.2.1

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by MarijnS95** [comment]
Can we get a new release with this, also for `image`? `image` itself is already using `jpeg-decoder 0.2` and this is showing as a duplicate dependency for us.

**Comment by CryZe** [comment]
@MarijnS95 You may want to run `cargo update` if you see multiple dependencies.

**Comment by MarijnS95** [comment]
@CryZe `cargo update` still adheres to semver. The released version of `image-tiff` points to `jpeg-decoder 0.1.17` so it is disallowed from using `0.2`.

**Comment by emilk** [comment]
A minor release should do, and would be much appreciated! `jpeg-decoder` is a rather large dependency to have duplicated

**Pull request merged**
