### PR TITLE
WIP: LZW encoding TIFF files

### PR DESCRIPTION
**Pull request by aspenluxxxy**

### CODE REVIEW

**Comment by fintelia** [comment]
It looks like this accidentally converted spaces to tabs across a whole bunch of files

**Comment by aspenluxxxy** [comment]
fixed

**Comment by aspenluxxxy** [comment]
why is this building locally but not on CI

**Comment by fintelia** [comment]
The failing CI build was with the 1.34 version of the Rust compiler. It looks like the other ones gets canceled if that fails.

**Comment by HeroicKatora** [comment]
The edition was upgraded to 2018, I believe this should work on 1.34 now.

**Pull request closed without merging**
